const { readFileSync } = require('node:fs');
const assert = require('node:assert/strict');
const { PGlite } = require(process.env.PGLITE_MODULE || '@electric-sql/pglite');
(async () => {
 const db = new PGlite();
 await db.exec(`create role anon; create role authenticated; create role service_role;
 create schema auth;
 create function auth.uid() returns uuid language sql as $$select nullif(current_setting('test.uid',true),'')::uuid$$;
 create function public.current_app_date() returns date language sql as $$select current_date$$;
 create table events(id uuid primary key, owner_id uuid, slug text,status text,end_date date,storage_folder text);
 create table guests(id uuid primary key,event_id uuid,name text);
 create table media(id uuid primary key,event_id uuid,guest_id uuid,created_at timestamptz,status text,storage_path text,thumbnail_path text);
 insert into events values('00000000-0000-0000-0000-000000000001','00000000-0000-0000-0000-000000000010','test','inactive',current_date-1,'test');
 insert into media values('00000000-0000-0000-0000-000000000002','00000000-0000-0000-0000-000000000001',null,now(),'uploaded','test/original.jpg','test/thumb.jpg');`);
 await db.exec(readFileSync('supabase/migrations/20260911_guest_gallery.sql','utf8'));
 const call = async sql => (await db.query(`select ${sql} as result`)).rows[0].result;
 const event = "'00000000-0000-0000-0000-000000000001'";
 await assert.rejects(call(`manage_gallery_share(${event},true)`));
 await db.exec(`set test.uid='00000000-0000-0000-0000-000000000010'`);
 assert.equal((await call(`guest_gallery_access('test')`)).closed,true);
 assert.equal((await call(`manage_gallery_share(${event},true)`)).enabled,true);
 assert.equal((await call(`guest_gallery_access('test')`)).photos.length,1);
 assert.equal((await call(`guest_gallery_access('test','00000000-0000-0000-0000-000000000002',false)`)).path,'test/thumb.jpg');
 assert.equal((await call(`guest_gallery_access('test','00000000-0000-0000-0000-000000000002',true)`)).path,'test/original.jpg');
 await db.exec("update media set storage_path='other-event/private.jpg'");
 assert.equal(await call(`guest_gallery_access('test','00000000-0000-0000-0000-000000000002',true)`),null);
 assert.equal(await call(`guest_gallery_access('test','00000000-0000-0000-0000-000000000099',true)`),null);
 await call(`manage_gallery_share(${event},false)`);
 assert.equal((await call(`guest_gallery_access('test')`)).closed,true);
 await call(`manage_gallery_share(${event},true)`);
 await db.exec('update gallery_shares set requests_used=1999');
 assert.equal((await call(`guest_gallery_access('test')`)).photos.length,1);
 assert.equal((await call(`guest_gallery_access('test')`)).closed,true);
 await call(`manage_gallery_share(${event},false)`);
 assert.equal((await call(`manage_gallery_share(${event},true)`)).requests_used,2000);
 await db.exec("update gallery_shares set requests_used=0,expires_at=now()-interval '1 second'");
 assert.equal((await call(`guest_gallery_access('test')`)).closed,true);
 await db.exec('update events set end_date=current_date');
 await assert.rejects(call(`manage_gallery_share(${event},true)`));
 await db.exec('update events set end_date=current_date-15');
 await assert.rejects(call(`manage_gallery_share(${event},true)`));
 await db.exec('update events set end_date=current_date-13; update gallery_shares set enabled=false');
 const nearArchive = await call(`manage_gallery_share(${event},true)`);
 assert(new Date(nearArchive.expires_at).getTime()-Date.now()<3*86400000, 'Sharing must end before archival');
 assert.equal(await call(`guest_gallery_access('wrong-link')`),null);
 assert.equal(await call("has_function_privilege('anon','public.guest_gallery_access(text,uuid,boolean,integer,text,boolean)','EXECUTE')"),false);
 assert.equal(await call("has_function_privilege('authenticated','public.guest_gallery_access(text,uuid,boolean,integer,text,boolean)','EXECUTE')"),false);
 await db.close();
 console.log('Gallery SQL: ownership, expiry, current event, quota, disable, missing photo/link and RPC permissions passed.');
})().catch(error => { console.error(error); process.exitCode=1; });
