const { PGlite } = require('@electric-sql/pglite');
const fs = require('node:fs');
const assert = require('node:assert/strict');
(async () => {
 const db = new PGlite();
 try {
  await db.exec(`create role anon; create role authenticated; create role service_role;
   create schema auth;create schema storage;
   create function auth.uid() returns uuid language sql as $$select '00000000-0000-0000-0000-000000000010'::uuid$$;
   create function current_app_date() returns date language sql as $$select current_date$$;
   create table events(id uuid primary key,owner_id uuid,storage_folder text,status text,start_date date,end_date date,cover_image_path text);
   create table guests(id uuid primary key,event_id uuid);
   create table media(id uuid primary key,event_id uuid,guest_id uuid,storage_path text,thumbnail_path text,file_type text,file_size bigint,status text);
   create table storage.objects(bucket_id text,name text);`);
  await db.exec(fs.readFileSync('supabase/migrations/20260912_media_reliability.sql','utf8'));
  const migration = fs.readFileSync('supabase/migrations/20260912_r2_storage.sql','utf8');
  await db.exec(migration); await db.exec(migration);
  const e='00000000-0000-0000-0000-000000000001',g='00000000-0000-0000-0000-000000000002',m='00000000-0000-0000-0000-000000000003',owner='00000000-0000-0000-0000-000000000010';
  await db.query(`insert into events values($1,$2,'event','active',current_date,current_date,null)`,[e,owner]);
  await db.query('insert into guests values($1,$2)',[g,e]);
  await db.query(`select prepare_photo_upload($1,$2,$3,'event/photo.webp','event/thumb.webp','image/webp',100)`,[m,e,g]);
  const reserve = (path,token='a'.repeat(64),checksum='A'.repeat(43)+'=') => db.query('select * from reserve_r2_object($1,$2,$3,null,$4,$5,100,\'image/webp\')',[path,m,g,checksum,token]);
  const legacyKey = (await reserve('event/photo.webp')).rows[0].object_key;
  const folders = fs.readFileSync('supabase/migrations/20260912_r2_id_folders.sql','utf8');
  await db.exec(folders); await db.exec(folders);
  assert.equal((await reserve('event/photo.webp')).rows[0].object_key,legacyKey);
  await assert.rejects(reserve('other/photo.webp'));
  await assert.rejects(reserve('event/photo.webp','b'.repeat(64)));
  await assert.rejects(reserve('event/photo.webp','a'.repeat(64),'B'.repeat(43)+'='));
  const thumbKey = (await reserve('event/thumb.webp')).rows[0].object_key;
  assert.ok(thumbKey.startsWith(`events/${e}/guests/${g}/thumb-`));
  assert.ok(thumbKey.endsWith('.webp'));
  assert.equal((await reserve('event/thumb.webp')).rows[0].object_key,thumbKey);
  const coverPath = `event-covers/${e}/test.webp`;
  await db.query('insert into cover_cleanup(event_id,path) values($1,$2)',[e,coverPath]);
  const cover = await db.query("select * from reserve_r2_object($1,null,null,$2,$3,$4,100,'image/webp')",[coverPath,owner,'A'.repeat(43)+'=','a'.repeat(64)]);
  assert.ok(cover.rows[0].object_key.startsWith(`events/${e}/covers/`));
  await assert.rejects(db.query('select complete_r2_photo($1,$2)',[m,'a'.repeat(64)]));
  await db.exec("update r2_objects set status='ready'");
  await db.query('select complete_r2_photo($1,$2)',[m,'a'.repeat(64)]);
  const allowed = async user => (await db.query("select r2_path_allowed('event/photo.webp',$1,false) as allowed",[user])).rows[0].allowed;
  assert.equal(await allowed(owner),true);
  assert.equal(Boolean(await allowed(null)),false);
  assert.equal(Boolean(await allowed(g)),false);
  await db.exec("update events set status='inactive'");
  await assert.rejects(reserve('event/photo.webp'));
  await assert.rejects(db.query('select complete_r2_photo($1,$2)',[m,'a'.repeat(64)]));
  assert.equal((await db.query("select has_table_privilege('anon','r2_objects','SELECT') as allowed")).rows[0].allowed,false);
  assert.equal((await db.query("select has_function_privilege('anon','complete_r2_photo(uuid,text)','EXECUTE') as allowed")).rows[0].allowed,false);
  console.log('R2 SQL: idempotence, path/owner isolation, immutable reservations, pending files, inactive event and service-only permissions passed.');
 } finally { await db.close(); }
})().catch(error=>{console.error(error);process.exitCode=1});
