const assert = require('node:assert/strict');
(async () => {
 const { handle, services, default: worker } = await import('../cloudflare/media-worker.js');
 const env={MEDIA_SIGNING_SECRET:'a'.repeat(48),ALLOWED_ORIGINS:'https://app.example'};
 const request=(path,body)=>new Request('https://media.example'+path,body?{method:'POST',body:JSON.stringify(body)}:{});
 const api={rpc:async()=>false,db:async()=>{throw new Error('Unexpected storage lookup')},client:{send:async()=>{throw new Error('Unexpected object read')}}};
 let response=await handle(request('/sign',{paths:['event/private.webp']}),env,api);
 assert.equal((await response.json())[0].signedUrl,null);
 response=await handle(request('/object?access={}&signature=forged'),env,api);
 assert.equal(response.status,403);
 response=await handle(request('/guest-gallery?slug=example'),env,{...api,rpc:async()=>({closed:true})});
 assert.equal(response.status,403);
 response=await handle(request('/remove',{paths:['event/private.webp']}),env,api);
 assert.equal(response.status,403);
 response=await worker.fetch(new Request('https://media.example/sign',{method:'OPTIONS',headers:{Origin:'https://evil.example'}}),env);
 assert.equal(response.status,403);
 response=await worker.fetch(new Request('https://media.example/sign',{method:'OPTIONS',headers:{Origin:'https://app.example'}}),env);
 assert.equal(response.headers.get('Access-Control-Allow-Origin'),'https://app.example');
 assert.equal(response.headers.get('Cache-Control'),'no-store');
 const signingApi={...api,rpc:async()=>true};
 response=await handle(request('/sign',{paths:['cover.webp']}),env,signingApi);
 const signed=(await response.json())[0].signedUrl;
 response=await handle(new Request(signed),env,api);
 assert.equal(response.status,403,'Access must be rechecked even for a valid signature');
 const signingEnv={...env,R2_BUCKET:'test',R2_ENDPOINT:'https://example.r2.cloudflarestorage.com',R2_ACCESS_KEY_ID:'test',R2_SECRET_ACCESS_KEY:'test'};
 const signedUploadApi={...services(signingEnv),rpc:async()=>({status:'uploading',object_key:'objects/test',file_type:'image/webp',file_size:100,checksum:'A'.repeat(43)+'='})};
 response=await handle(request('/upload',{token:'00000000-0000-0000-0000-000000000001'}),signingEnv,signedUploadApi);
 const upload=await response.json();
 const signedHeaders=new URL(upload.url).searchParams.get('X-Amz-SignedHeaders');
 for(const header of ['content-length','content-type','x-amz-checksum-sha256']) assert(signedHeaders.includes(header));
 assert.equal(new URL(upload.url).searchParams.get('X-Amz-Expires'),'300');
 console.log('R2 Worker: denied paths, forged signatures, disabled gallery, unauthenticated deletion, CORS and read-time revocation passed.');
})().catch(error=>{console.error(error);process.exitCode=1});
